### ISSUE TITLE
Missing Babel config associations

### ISSUE THREAD

**Issue by jdreesen** [mallowigi/iconGenerator#2]
Babel (config) is currently associated with:
- .babelrc
- .babelrc.js
- .languagebabel
- .babel
- babel.json
- babel.config.json

See: 
- http://www.material-theme.com/docs/reference/associations/#babel 
- http://www.material-theme.com/docs/reference/associations/#babel-config

---

According to https://babeljs.io/docs/en/config-files#supported-file-extensions Babel supports the followig config file names:
- .babelrc
- .babelrc.json
- .babelrc.js
- .babelrc.cjs
- .babelrc.mjs
- babel.config.json
- babel.config.js
- babel.config.cjs
- babel.config.mjs

---

I would create a PR but I'm not sure where to add it. 
Is it https://github.com/mallowigi/iconGenerator/blob/master/icon_associations.json 
or https://github.com/mallowigi/iconGenerator/blob/master/icon_associations.xml 
or maybe https://github.com/mallowigi/iconGenerator/blob/master/config_original.cson ?

**Comment by mallowigi** [comment]
from the docs: 
> ^babel(\.[\w\-]+)?\.json$
> ^\.(babelrc(\.js)?\|languagebabel\|babel)$

so .babelrc, .babelrc.js, babel.config.json are supported

The only missing are `.babelrc.json`, `.babelrc.cjs`, `.babelrc.mjs`, `babel.config.js`, `babel.config.cjs`, `babel.config.mjs`

About the mjs and cjs files, I explicitely removed it for now as I don't know the frequency of people using cjs or mjs extensions, I haven't encountered them insofar. I'll think about it.

**Comment by jdreesen** [comment]
> from the docs:
> 
> > ^babel(.[\w-]+)?.json$
> > ^.(babelrc(.js)?|languagebabel|babel)$
> 
> so .babelrc, .babelrc.js, babel.config.json are supported
> 
> The only missing are `.babelrc.json`, `.babelrc.cjs`, `.babelrc.mjs`, `babel.config.js`, `babel.config.cjs`, `babel.config.mjs`

That's correct.

> About the mjs and cjs files, I explicitely removed it for now as I don't know the frequency of people using cjs or mjs extensions, I haven't encountered them insofar. I'll think about it.

You may be right.
The docs say:
> `babel.config.js` and `.babelrc.js` behave like the `.mjs` equivalents when your `package.json` file contains the `"type": "module"` option, otherwise they are exactly the same as the `.cjs` files.

So probably most people just use the `.js` files. 

---

It would be great if `.babelrc.json` and `babel.config.js` could be added for now.
