### ISSUE TITLE
Unable to checkout repo on Windows

### ISSUE THREAD

**Issue by pjpscriv** [mallowigi/iconGenerator#8]
The files in `examples/files/` mean the repo cannot be checked out on Windows. `*` is a disallowed filename character on Windows. Relevant StackOverflow [here](https://stackoverflow.com/questions/26780189/cant-clone-git-repo-on-windows-when-some-file-names-contain-asterisk).

This is what cloning looks like:
```
> git clone https://github.com/mallowigi/iconGenerator.git
Cloning into 'iconGenerator'...
remote: Enumerating objects: 2592, done.
remote: Counting objects: 100% (2592/2592), done.
remote: Compressing objects: 100% (1545/1545), done.
remote: Total 2592 (delta 1232), reused 2383 (delta 1037), pack-reused 0R
Receiving objects: 100% (2592/2592), 14.87 MiB | 7.26 MiB/s, done.
Resolving deltas: 100% (1232/1232), done.
error: invalid path 'examples/files/*.pyc'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

A minor issue that can be worked around but I thought I would flag it as a pain point. 🙂

**Comment by mallowigi** [comment]
I am not a windows user but I can imagine why it could be an issue.

In any case the examples should not have been committed and pushed. I'll fix that soon. Thanks!

**Comment by mallowigi** [comment]
fixed.

**Comment by pjpscriv** [comment]
Cheers :)
